name: Deploy to Itch.io

# Se déclenche uniquement sur les tags qui commencent par 'v' (ex: v1.0.0)
on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js avec la version du projet
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'npm'

      # 3. Installation des dépendances
      - name: Install dependencies
        run: npm ci

      # 4. Build du projet
      - name: Build project
        run: npm run build

      # 5. Déploiement sur Itch.io
      - name: Deploy to Itch.io
        uses: yeslayla/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: html5
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: dist
          VERSION: ${{ github.ref_name }}
